### PR TITLE
Allow generic option collection in templating parameters

### PR DESCRIPTION
**Pull request by enebo**
This is a transitional PR which allows extra attributes of parameters from config.yml to get saved as 'options' to the parameter we interact with when generating code via ERB.

Why? In my current branch I have marked syntactical tokens that execution is uninterested in serializing (and then loading into an AST) as 'exclude: execute'.  My templates for serialize.c, Nodes.java, and Loader.java then will skip those elements altogether. I can think of other useful attributes we can put in to help with generation.

### CODE REVIEW

**Comment by enebo** [comment]
I have signed CLA after I saw that fail.

**Comment by enebo** [comment]
I removed \#param from all the param types because nothing seems to call it.

**Comment by eregon** [comment]
This sounds good to me. Could you also include the changes to the templates in this PR? I think that makes it easier to review and see how it's used.

**Comment by enebo** [comment]
@eregon What I have on my playground branch is quite a bit different but I will add this to 'java' templates (since i think we both want this in some form) so you can see how it is used.

**Comment by enebo** [comment]
@eregon I will add another PR for the exclude stuff to java templates so you can see this and hopefully also want the same set of excludes.

**Pull request merged**
